### PR TITLE
Upgrade dependencies & upgrade testing

### PR DESCRIPTION
**Pull request by j-rewerts**
Merged in @slmyers changes. 
 - running `npm run unit-test` will run unit tests
 - running `npm run integration-test` will run integration tests

Our integration tests depend on Elasticsearch. We have a script, originally built by @slmyers to stand all this up automatically. I've added a guide if people want to debug their integration tests.

I'll need to add waaay more tests in the future, but this will at least get @CodyGramlich rolling on the backend.

### CODE REVIEW

**Comment by j-rewerts** [comment]
@slmyers Would you mind reviewing this with me? It includes all of the content of #44, so we can either close that, or merge it. It also has some minor changes to how testing is done on the backend.

**Comment by slmyers** [comment]
I need to do a bit more tweaking on #44 (some CSS/style stuff) but once that's done i'll close #44 and merge into this one + review.

**Comment by j-rewerts** [comment]
Great! When you go to submit your code, you should see j-rewerts:new-tests as a valid location to submit a PR to. The other thing I could do is just give you write access to my fork.

**Comment by slmyers** [comment]
Damn, nice work. I'll try to finish up my stuff and review soon, but tonight is premier of season 2 of Star Trek, so it will have to wait 😄

**Comment by slmyers** [comment]
fixes (#42) and (#45) (45 requires merge on your repo)

**Comment by j-rewerts** [comment]
We have a bit of an overflow on one of our main page buttons.
screen shot 2019-01-22 at 1 04 37 pm
 I'll see if I can resolve it.

**Comment by slmyers** [comment]
LGTM

**Comment by j-rewerts** [comment]
Great! Merging.

**Pull request merged**
