### PR TITLE
Issue 32 -- update client dependencies (WIP)

### PR DESCRIPTION
**Pull request by slmyers**
* update Angular, rxjs, ngrx, `@angular/material`
* generated new project using up to date `@angular/cli` and copied the generated files into this project.
* fixed (#42) -- update `nodemon` dependency in backend.
* works on my machine
* will be basing (#10) and (#11) off of this branch

### CODE REVIEW

**Comment by j-rewerts** [comment]
Thanks @slmyers! This is going to be quite the PR review 😄 . I'll be working through this with one of my new coop.

**Comment by CodyGramlich** [comment]
Hello @slmyers! I am one of the new coop students working with Jared and I will be working on YouCanBenefit.

**Comment by slmyers** [comment]
Still fixing some things.

**Comment by j-rewerts** [comment]
Closing. See #47 for a more up to date branch.

**Pull request closed without merging**
