### PR TITLE
Issue 7 - remove dependence on proxying requests

### PR DESCRIPTION
**Pull request by j-rewerts**
This PR made it easier for the client app to talk to the API.
 - update RxJS
 - update NestJS
 - Added a variable for API host

### CODE REVIEW

**Comment by j-rewerts** [comment]
@farhadmak Could you check out this PR and verify it's working for local dev?

**Comment by j-rewerts** [comment]
Btw, closes #7

**Comment by farhadmak** [comment]
can confirm this works on Ubuntu WSL.

**Comment by j-rewerts** [comment]
Perfect. Merging in.

**Pull request merged**
